#spring.application.name=eureka-feign-upload-client
#server.port=2101
#
#eureka.client.serviceUrl.defaultZone=http://localhost:1001/eureka/

spring:
  application:
    name: eureka-feign-upload-client

server:
  port: 2102

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/