#spring.application.name=turbine
#
#server.port=8989
#management.port=8990
#
#eureka.client.serviceUrl.defaultZone=http://localhost:1001/eureka/
#
#turbine.app-config=eureka-consumer-ribbon-hystrix
#turbine.cluster-name-expression="default"
#turbine.combine-host-port=true
spring:
  application:
    name: turbine

server:
  port: 8989

#management:
#  server:
#    port: 8990

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

turbine:
  app-config: eureka-consumer-ribbon-hystrix
  cluster-name-expression: "'default'"
  combine-host-port: true
  aggregator:
    cluster-config: default

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#      base-path: /

#Spring Boot 2.0 的Actuator只暴露health和info
#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'