#spring.application.name=eureka-feign-upload-server
#server.port=2101
#
#eureka.client.serviceUrl.defaultZone=http://localhost:1001/eureka/

spring:
  application:
    name: eureka-feign-upload-server

server:
  port: 2101

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/