#spring.application.name=eureka-consumer-ribbon-hystrix
#server.port=2101
#
#eureka.client.serviceUrl.defaultZone=http://localhost:1001/eureka/

spring:
  application:
    name: eureka-consumer-ribbon-hystrix

server:
  port: 2101

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

#针对spring boot 2.0和spring cloud Finchley.M8这类的版本出现Unable to connect to Command Metric Stream。是因为，默认其实的切入点是：/actuator/hystrix.stream。要改成/hystrix.stream：
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#      base-path: /

management:
  endpoints:
    web:
      exposure:
        include: '*'