#spring.application.name=turbine-amqp
#
#server.port=8989
#management.port=8990
#
#eureka.client.serviceUrl.defaultZone=http://localhost:1001/eureka/
spring:
  application:
    name: turbine-amqp
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8989

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
